### ISSUE TITLE
Task.Run for synchronous call dead locks

### ISSUE THREAD

**Issue by volkanakinpasa** [JohnnyCrazy/SpotifyAPI-NET#317]
I am getting an error from my project when I call **synchronous** method which is "GetPrivateProfile"()". This only happens when two request is being sent at the same time(like in 1,2 seconds). I assume the first call is still blocking the other request. Therefore the second request can't make it. 
**Please keep mind: My hosting provider doesn't allow me to use multi thread.** 
Maybe the suggestion can be not using Task.Run in synchronous method. Or If anyone thinks that I am mistaken, please correct me. 

Error
> One or more errors occurred. -    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
  at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
  at System.Threading.Tasks.Task`1.get_Result()
  at SpotifyAPI.Web.SpotifyWebClient.DownloadRaw(String url, Dictionary`2 headers)
  at SpotifyAPI.Web.SpotifyWebClient.Download(String url, Dictionary`2 headers)
  at SpotifyAPI.Web.SpotifyWebClient.DownloadJson[T](String url, Dictionary`2 headers)
  at SpotifyAPI.Web.SpotifyWebAPI.DownloadDataAlt[T](String url)
  at SpotifyAPI.Web.SpotifyWebAPI.DownloadData[T](String url)
  at SpotifyAPI.Web.SpotifyWebAPI.GetPrivateProfile()

Here is my method 
https://github.com/volkanakinpasa/Paradify/blob/master/paradify.net/web/Services/Implementations/UserService.cs
   
                
            public PrivateProfile GetMe(Token token)
                {
                    SpotifyWebAPI api = new SpotifyWebAPI() { AccessToken = token.AccessToken, TokenType = token.TokenType };
                    return api.GetPrivateProfile();       
                }

**Comment by JohnnyCrazy** [comment]
We need Task.Run because the HTTPClient does not provide sync methods.
I think the culprit is your provider, or does it also bit work locally ?

**Comment by volkanakinpasa** [comment]
Yes! I see, I was actually going to suggest System.Net.WebClient.DownloadData() for sync  request. But, If you haven't got any request like this from others(probably not...), I will find a solution on my side.
