### ISSUE TITLE
Error in SpotifyWebClient.cs when trying to fetch PlaybackState

### ISSUE THREAD

**Issue by MorGuux** [JohnnyCrazy/SpotifyAPI-NET#330]
Hi,

I have the code working perfectly, but occasionally I get an error which freezes the software (I'm writing a plugin for other software), and just hangs.

![image](https://user-images.githubusercontent.com/18599017/54915656-91b1a700-4eef-11e9-86dc-4648da8f4667.png)

> System.InvalidOperationException
  HResult=0x80131509
  Message=Collection was modified; enumeration operation may not execute.
  Source=mscorlib
  StackTrace:
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Enumerator.MoveNext()
   at System.Net.Http.Headers.HttpHeaders.AddHeaders(HttpHeaders sourceHeaders)
   at System.Net.Http.Headers.HttpRequestHeaders.AddHeaders(HttpHeaders sourceHeaders)
   at System.Net.Http.HttpClient.PrepareRequestMessage(HttpRequestMessage request)
   at System.Net.Http.HttpClient.SendAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.GetAsync(Uri requestUri, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.GetAsync(String requestUri)
   at SpotifyAPI.Web.SpotifyWebClient.<>c__DisplayClass10_0.<DownloadRaw>b__0() in E:\Downloads\SpotifyAPI-NET-master\SpotifyAPI.Web\SpotifyWebClient.cs:line 45
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

**Comment by MorGuux** [comment]
I think it's to do with if Spotify isn't running, or a song hasn't been played.

**Comment by JohnnyCrazy** [comment]
Mh...this maybe has to do with the headers collection...do you have the full stacktrace? @MorGuux

**Comment by MorGuux** [comment]
I'm not sure tbh, I'll have to look over my code again (it's been a while since I saw it :D)

If I remember correctly, it only occured if a song hasn't been played (or spotify hadn't been opened, thus no song) since a new token was accessed.

**Comment by JohnnyCrazy** [comment]
Yea I have the feeling this maybe occurs when the Spotify access token is updated and a request is currently in-flight. I will try to reproduce it, but if you can confirm sth like this, would make it easier :P 👍

**Comment by MorGuux** [comment]
Yeah no worries, just reinstalled Windows 10, so gotta get Visual Studio up and running :D

**Comment by JohnnyCrazy** [comment]
In v6 we switched from the `DefaultHeaders` to having a seperated `HttpRequestMessage` for each request. This error thus should not occur in the latest version.

If you have more feedback/problems/suggestions, feel free to reply here or open another issue!
