### ISSUE TITLE
GetRecommendationGenres throws SpotifyAPI.Web.APIException: invalid request

### ISSUE THREAD

**Issue by SKProCH** [JohnnyCrazy/SpotifyAPI-NET#487]
After calling `await spotify.Browse.GetRecommendationGenres();` i get this exception:
```
SpotifyAPI.Web.APIException: invalid request
   at SpotifyAPI.Web.Http.APIConnector.ProcessErrors(IResponse response)
   at SpotifyAPI.Web.Http.APIConnector.DoRequest(IRequest request)
   at SpotifyAPI.Web.Http.APIConnector.DoSerializedRequest[T](IRequest request)
   at SpotifyAPI.Web.Http.APIConnector.SendAPIRequest[T](Uri uri, HttpMethod method, IDictionary`2 parameters, Object body, IDictionary`2 headers)
   at TimeLoose.Program.OnImplicitGrantReceived(Object sender, ImplictGrantResponse response) in ...\Program.cs:line 33
```
What i doing wrong?

Library version - 6.0.0-beta.9

**Comment by JohnnyCrazy** [comment]
Seems like a wrong URI is used in that call, will push a fix today! Thanks for the report :)

**Comment by JohnnyCrazy** [comment]
This is now fixed in master. Will be released with the end of the week (If you need the fix urgent, feel free to grab the latest binaries from the CI/CD Pipeline).

Thanks again!
