### ISSUE TITLE
SpotifyAPI.Web.Http.IResponse response ProcessError

### ISSUE THREAD

**Issue by RSvlad** [JohnnyCrazy/SpotifyAPI-NET#812]
Everything is working fine on my samsung phone, but my friend has issues on his xiaomi, I'm working inside of xamarin forms for android, if it means anything

Here's the exception:
Message: Exception of type 'SpotifyAPI.Web.APIException' was thrown.
StackTrace:   at SpotifyAPI.Web.Http.APIConnector.ProcessErrors (SpotifyAPI.Web.Http.IResponse response) [0x00058] in <bd6e4f2ac046405a91b1903603aa39a6>:0 
  at SpotifyAPI.Web.Http.APIConnector.DoRequest (SpotifyAPI.Web.Http.IRequest request) [0x00247] in <bd6e4f2ac046405a91b1903603aa39a6>:0 
  at SpotifyAPI.Web.Http.APIConnector.DoSerializedRequest[T] (SpotifyAPI.Web.Http.IRequest request) [0x00086] in <bd6e4f2ac046405a91b1903603aa39a6>:0 
  at SpotifyAPI.Web.Http.APIConnector.SendAPIRequest[T] (System.Uri uri, System.Net.Http.HttpMethod method, System.Collections.Generic.IDictionary`2[TKey,TValue] parameters, System.Object body, System.Collections.Generic.IDictionary`2[TKey,TValue] headers) [0x00095] in <bd6e4f2ac046405a91b1903603aa39a6>:0 
  at MyProgram.Main.Playlists_Clicked (System.Object sender, System.EventArgs e) [0x00093] in <608f8fcc9d814efbb22da1b695ab6a9d>:0 
Source: mscorlib
TargetSite: Void Throw()

**Comment by RSvlad** [comment]
[This](https://github.com/JohnnyCrazy/SpotifyAPI-NET/issues/487) issue seems similar to mine, not sure if I can help out somehow

**Comment by RSvlad** [comment]
Moved to .net maui, here's what the exception looks there:

Message: Exception_WasThrown, SpotifyAPI.Web.APIException
StackTrace:    at SpotifyAPI.Web.Http.APIConnector.ProcessErrors(IResponse response)
   at SpotifyAPI.Web.Http.APIConnector.DoRequest(IRequest request)
   at SpotifyAPI.Web.Http.APIConnector.<DoSerializedRequest>d__30`1[[SpotifyAPI.Web.SearchResponse, SpotifyAPI.Web, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
   at SpotifyAPI.Web.Http.APIConnector.<SendAPIRequest>d__34`1[[SpotifyAPI.Web.SearchResponse, SpotifyAPI.Web, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
   at MyProgram.MainPage.ButtonFind_Clicked(Object sender, EventArgs e)
Source: SpotifyAPI.Web
TargetSite: Void ProcessErrors(SpotifyAPI.Web.Http.IResponse)

**Comment by RSvlad** [comment]
Found the issues with the http logger, I didn't give access individually in the spotify dashboard
